### ISSUE TITLE
Upgrade of NovaSeq Control Software

### ISSUE THREAD

**Issue by AnnaZetterlund** [Clinical-Genomics/demultiplexing#111]
Illumina have released a new version of the NovaSeq Control Software and this will have some downstream implications. 

Please have a look at the customer notification sent out by illumina. https://sharecontent.illumina.com/i/KfX4vPLUSSIGNUKxly8e9SwY7aQiZU7qICRBkAIYFPjs6ZkhMkbwnGh66Yek96U6yZrCav___QIh8x0E0pymUQDGIt8c0u___9b5vNdfcju2WAPi41hPKYEQUALSIGN

The thing we need to look into is that the reverse complement workflow will replace the existing forward strand
workflow as the default indexing workflow in NVCS 1.7

The NVCS version used is stated in the RunParameters.xml file created by the Novaseq when the run is started. 

What makes things complicated is that we can upgrade the instruments and run with the old sequencing kits (v1.0) and then the index will be the old way. We have old kits to run until beginning of December. In that case I expect a recipe to have a different version in the RunParameters.xml than if running with Sequencing kit v1.5. I can't find the version of the Sequencing kit used in any xml file or in LIMS otherwise it would be the easiest thing to use to start an IF formula... (I can investigate this further if you think that is the best way)

From the lab side we would like to verify this change as soon as possible since we may need to run for example an express sample on a smaller FC which will have the new version of the kit. 

One NovaSeq out of three is now upgraded.

**Comment by barrystokman** [comment]
@AnnaZetterlund is there an example of a RunParameters.xml from a run using Novaseq Control Software version 1.7.0 that used reagent kit 1.5? And one that used 1.0?

NGI selects the reagent kit version in LIMS when setting up a run. @mayabrandi is it possible to implement this for us?

**Comment by AnnaZetterlund** [comment]
@barrystokman we have not run any with the new kit. I know that NGI has run with kit 1.0 on NVCS 1.7.0. I could ask them to share that basespace run with us.

**Comment by barrystokman** [comment]
that would be great!

**Comment by barrystokman** [comment]
@AnnaZetterlund any news from NGI about the basespace run?

**Comment by AnnaZetterlund** [comment]
> @AnnaZetterlund any news from NGI about the basespace run?

I think they forgot about it. I have now reminded them...

**Comment by barrystokman** [comment]
PRs ready for review https://github.com/Clinical-Genomics/demultiplexing/pull/123 and https://github.com/Clinical-Genomics/servers/pull/461!

**Comment by henrikstranneheim** [comment]
@AnnaZetterlund Can we close this?

**Comment by henrikstranneheim** [comment]
Actually closing this - please reopen if you disagree
