### ISSUE TITLE
Test bcl2fastq on Hasta

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#125]
bcl2fastq needs to be tested on hasta. ~It's important to note that the version of bcl2fastq on hasta and thalamus differ:~ The script `demux-novaseq.bash` actually uses `/usr/local/bcl2fastq/bin/bcl2fastq`, which version matches the version of bcl2fastq on hasta.

`bcl2fastq -- version` on hasta:
```
BCL to FASTQ file converter
bcl2fastq v2.20.0.422
Copyright (c) 2007-2017 Illumina, Inc.
```

`/usr/local/bcl2fastq/bin/bcl2fastq --version` on thalamus:
```
BCL to FASTQ file converter
bcl2fastq v2.20.0.422
Copyright (c) 2007-2017 Illumina, Inc.
```

### Novaseq demultiplexing bcl2fastq command:
```
${BCL2FASTQ_BIN} --loading-threads 3 --processing-threads 15 --writing-threads 3 --runfolder-dir ${IN_DIR} --output-dir ${OUT_DIR}/${UNALIGNED_DIR} --use-bases-mask ${BASEMASK} --sample-sheet ${IN_DIR}/SampleSheet.csv --barcode-mismatches 1
```
${BCL2FASTQ_BIN} = /usr/local/bcl2fastq/bin/bcl2fastq (declared in `demux-novaseq.bash`)
${IN_DIR} = input parameter
${OUT_DIR} = derived in script
${UNALIGNED_DIR} = derived in script
${BASEMASK} = derived in script using `demux basemask create --application nova ${IN_DIR}`

### HiSeq2500 demultiplexing bcl2fastq command:
```
/usr/local/bin/configureBclToFastq.pl --force --sample-sheet ${BASE}/Data/Intensities/BaseCalls/SampleSheet.csv --ignore-missing-bcl --ignore-missing-stats --use-bases-mask ${BASEMASK} --fastq-cluster-count 0 --input-dir ${BASE}/Data/Intensities/BaseCalls --output-dir ${DEMUX_DIR}/${RUN}/${UNALDIR} 2>&1 | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" >> ${PROJECTLOG}
```
I can find no reason why we can't demux 2500 FCs with `bcl2fastq` so perhaps we should replace `configureBclToFastq.pl`

**Comment by henrikstranneheim** [comment]
/usr/local/bcl2fastq/bin/bcl2fastq works. However, we are now using singularity containers instead
