### ISSUE TITLE
Keep Sequencing files for LIMS longer on Thalamus

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/demultiplexing#127]
LIMS are looking at some files in the run-folders when the flow cells are taken through NovaSeq Run step in LIMS. 
When there have been demux-problems and the flow cells have been demultiplexed again we have ended up in the problem that the runs have been removed from Thalamus before the LIMS-step has been done. 
LIMS can then  not reach the info needed for the step.
We want these files to be kept longer on Thalamus.

Files/dirs needed for LIMS: ??? @mayabrandi please help me here
InterOp
RunInfo.xml
RunParameters.xml

**Comment by mayabrandi** [comment]
I think those are the only once that are needed.

**Comment by henrikstranneheim** [comment]
We are moving from clincial.preproc and this is not relevant anymore
