### ISSUE TITLE
Change PDC retrieval of 2500/novaseq flowcells destination to hasta instead of thalamus

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#130]
Destination server is handled in the PDC API in cg: https://github.com/Clinical-Genomics/cg/blob/master/cg/apps/pdc.py

The destination path is handled in the cg config file in severs: https://github.com/Clinical-Genomics/servers/blob/master/config/hasta.scilifelab.se/cg.yaml

**Comment by henrikstranneheim** [comment]
Update
- fixed for Novaseq
- Part of https://github.com/Clinical-Genomics/demultiplexing/issues/136 to fix for 2500

**Comment by henrikstranneheim** [comment]
@barrystokman Is this done?

**Comment by barrystokman** [comment]
Yes, I'm closing it now.
