### ISSUE TITLE
Hasta demultiplexing test data

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#131]
Novaseq:

runs directory: `/home/proj/stage/flowcells/novaseq/runs/`
demux directory: `/home/proj/stage/flowcells/novaseq/demux/`

flowcells: 
 - `201209_A00689_0201_AHKYNCDSXY` (S4, NCSV 1.7, reagent kit 1.5)
- `201203_A00689_0200_AHVKJCDRXX` (S1, NCSV 1.6)
 - `201214_A00689_0204_AHW72JDRXX` (SP, Fluffy)

2500:
runs directory: `/home/proj/stage/flowcells/2500/runs/`
demux directory: `/home/proj/stage/flowcells/2500/demux/`

flowcells:

- tbd

**Comment by henrikstranneheim** [comment]
Test data is in place in stage
