### ISSUE TITLE
WIP Adjust demultiplexing bash scripts so they can run on hasta

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#132]
scripts involved:

novaseq demux
`https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/novaseq/checkfornewrun.bash`
`https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/novaseq/demux-novaseq.bash`

2500 demux
`https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/checkfornewrun.bash`
`https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/demux.bash`

delivery novaseq & 2500 results:
`https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/2-hiseq-deliver.bash`

2500 NIPT:
`https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/syncnipt.bash`

NIPT viewer?:

Note: best to be picked up together with the crontab settings

**Comment by henrikstranneheim** [comment]
@barrystokman Done?

**Comment by barrystokman** [comment]
Yes, closing.
