### ISSUE TITLE
Novaseq demultiplexing on Dragen

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#135]
bcl2fastq -> BCL Convert quick guide:
https://emea.support.illumina.com/bulletins/2020/10/upgrading-from-bcl2fastq-to-bcl-convert.html

current bcl2fastq command for NovaSeq:
```
bcl2fastq --loading-threads 3 --processing-threads 15 --writing-threads 3 --runfolder-dir ${RUN_DIR} --output-dir ${DEMUX_DIR}/${UNALIGNED_DIR} --use-bases-mask ${BASEMASK} --sample-sheet ${RUN_DIR}/SampleSheet.csv --barcode-mismatches 1
```

Converted BCL Convert command:
```
bcl-convert  --bcl-input-directory  ${RUN_DIR}  --output-directory ${DEMUX_DIR}/${UNALIGNED_DIR} --sample-sheet ${RUN_DIR}/SampleSheet.csv
```

Notes:
1. `--use-bases-mask` is not longer a command line option. Overriding cycles can be indicated in the samplesheet using `OverrideCycles,Y#;N#`. If using a standard dual index length 10 (padded or not) samplesheet for a NovaSeq flowcell, no `--use-bases-mask` or `OverrideCycles,Y#;N#` is needed.
2. The option `--barcode-mismatches` is removed and needs to be indicated in the samplesheet by using `BarcodeMismatchIndex1,#`, and `BarcodeMismatchIndex2,#`.

DRAGEN Overview:
https://emea.support.illumina.com/content/dam/illumina-marketing/documents/products/technotes/dragen-integration-tech-note-970-2020-006.pdf

DRAGEN USer Guide:
https://emea.support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/dragen-bio-it/dragen-bio-it-platform-v3.6-user-guide-1000000128306-00.pdf

**Comment by henrikstranneheim** [comment]
@barrystokman Done?

**Comment by barrystokman** [comment]
yes, closing
