### ISSUE TITLE
Name the fastq files from HiseqX demux to contain the sample_id as in Novaseq demultiplexing

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/demultiplexing#155]

**Comment by karlnyr** [comment]
Change the naming convention made when moving or linking the files in:
https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/hiseqx/xdemuxtiles.batch

Depending on what happens in https://github.com/Clinical-Genomics/demultiplexing/issues/157
we might change the NovaSeq way, thus the nomenclature to be used in HiseqX
