### ISSUE TITLE
NIPT Trending (snakemake)

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#37]
See https://docs.google.com/document/d/1Ky68MeEEX19tuKBVEOHA-wy_XWUWLo2YkPPgB_L_3ek/edit

**Comment by ingkebil** [comment]
I guess we can close this now? :)

**Comment by hassanfa** [comment]
Probably :). Should we create a repo for the workflow before closing it?

**Comment by ingkebil** [comment]
So, it depends on whether or not this was a one timer or not. If it is a one timer, I would prefer to not open yet-another-repo and ave the workflow in this repo. If you believe we will be using this a lot more, sure, go ahead :)

**Comment by hassanfa** [comment]
Agreed! We want to avoid YARs :-). Closing it then!
