### ISSUE TITLE
Create samplesheet for rapid automatically

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#39]
Rewrite the code for testing.

DoD:
- minor

**Comment by ingkebil** [comment]
Fixed in #45

**Comment by barrystokman** [comment]
After sprint 2

Connection with Thalamus is not working, IT is looking into it.

**Comment by emiliaol** [comment]
I think we decided to not do this?

**Comment by ingkebil** [comment]
At least not the rewrite for unit tests. The fetching of the sheet is already happening
