### ISSUE TITLE
Add pre-demux sanity check

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#4]
Issue a warning when following rules are violated:
- [x] index length runParameters is different than the length of the indexes in the SampleSheet
- [x] considering the length of the index in the runParamaters, are the indexes unique for each sample? No -> warning.

A warning could constitute of sending an email to clinical-bioinfo@.

This needs to be implemented for HiSeqX and HiSeq2500.

**Comment by robinandeer** [comment]
I think this could be accomplished through logging. Just specify a handler that will send the email on any "error" log events
