### ISSUE TITLE
implement automatic start of novaseq demux on thalamus

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#42]
Super used/Contact person: EOL

Problem description:
When a novaseq sequencing run is finished it needs to be demultiplexed without human interaction to be efficient. We now don't have monitoring of the run directory on thalamus, nor a script that kickstarts the demuxing.

Solution suggested:
1. base the demux_novaseq.bash script on the existing demux.bash on thalamus. Changes needs to be made to which software to be used, where to monitor finished runs, output directory...

pick up run
kickstart demux
transfer flowcell stats and linking fastq files to HK

dependent on: novaseq demux and parsing stats, see US ....

**Comment by ingkebil** [comment]
This is done already ;)
