### ISSUE TITLE
Automatic demultiplexing of flowcells holding indexes with different lengths on rapid

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#44]
As a TA member I want demulitplexing of flowcells to be handled automatically so that I can use my time for more important things.

Problem: When samples with two different index lengths are sequenced on the same rapid flow cell there is manually labour required to demultiplex one of the index lengths.

**Comment by emiliaol** [comment]
Closing this as we hardly run rapid sequencing anymore.
