### ISSUE TITLE
Demulitplexing must be able to fetch samplesheet from housekeeper

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#46]
As a member of TA, I would like to be able to access all available samplesheets from all runs so that I don't need to traverse the DEMUX dir structure in search of a samplesheet.

Problem:
The samplesheets used to be placed on https://tools.scilifelab.se, which is now defunct. All those sheets are not in LIMS and we should be able to still have access to them.

Suggested solution:
- [x] download all samplesheets from "tools" website
- [ ] some sample_ids are in the old "clinical genomics id" format which is no longer in use. Change all sample_ids in the sheets to the LIMS ids
- [ ] curate cgstats/cg and change all sample_ids to the LIMS ids
- [ ] put all samplesheets from the "tools" website into housekeeper. Make new bundle, add sheet, tag sheet with 'sheet' and the FC id.

Questions
Q1: Should be able to name the bundle like the FC instead as to group all FC related files?
A1:

How to demo:
`housekeeper get -V angrybird -t sheet -t $FC`

**Comment by henrikstranneheim** [comment]
Stale - reopen if needed
