### ISSUE TITLE
Send email on 2500 demux start to clinical-demux@scilifelab.se

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#47]
When demux'ing of an X starts, an email is sent to clinical.demux with the samplesheet. This email is used as an easy indication that demuxing has started successfully.

This should be implemented for 2500 demux starts.

Requirements: Email is sent to clinical-demux@scilifelab.se on successful starts with the sample sheet used attached to the email.

Actions:
* Add line to demux script for 2500 similar to how it is done for X ```cat ${RUNDIR}/SampleSheet.csv | mail -s "DEMUX of $FC started" ${EMAIL}```

Script on Thalamus is probably ```/home/hiseq.clinical/SCRIPTS/demux.bash```

DoD for minor update

**Comment by henrikstranneheim** [comment]
@emmser @karlnyr Do you still want this?

**Comment by henrikstranneheim** [comment]
@emmser @karlnyr Do you still want this?

**Comment by karlnyr** [comment]
This already exists, closing the issue
