### ISSUE TITLE
X10: Check for possible sample contamintion in undetermined indexes

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#5]
For an X10 run, check for significant percentage of indexes in the undetermined indexes that belong to our kits. See belong links for possible indexes used.

http://supportres.illumina.com/documents/documentation/chemistry_documentation/samplepreps_truseq/truseqsampleprep/truseq_sample_prep_pooling_guide_15042173_a.pdf

https://github.com/pekrau/samplesheet/blob/master/index_definitions.py

**Comment by henrikstranneheim** [comment]
Stale
