### ISSUE TITLE
Novaseq demultiplexes on Hasta

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#65]
As a TA member, I want demultiplexing of the novaseq set up on Hasta so that I can demultiplex an S4 at lightning speed! Arriba Arriba Hasta!

Problem: demux is not available nor is bcl2fastq.

Suggested solution:
- Ask IT to install bcl2fastq2: 
```
Hi guys

Can you install bcl2fastq 2.20 on hasta?

thanks!
```
- get one novaseq run (raw data, bcl files) from a nas (seq-nas-1, nas-6, or clinical-nas-2) to `/home/proj/stage/runs/novaseq`.
- create update-demux-{stage,prod}.sh script if not exists. The git repo need to be installed in `/home/proj/{stage,production}/bin/git/demultiplexing` to accomodate the bash scripts. The demux package can be in `P_main`.
- Add crontabs for hiseq.clinical, one for stage and one for production (only stage displayed here):
```
# NovaSeq demux [every 10 mins]
0,10,20,30,40,50 * * * * source /home/proj/stage/servers/resources/hasta.scilifelab.se/usestage.sh && /home/proj/stage/bin/git/demultiplexing/scripts/novaseq/checkfornewrun.bash /home/proj/stage/runs/novaseq/ /home/proj/stage/demultiplexed-runs/ &>> /home/proj/stage/logs/checkfornewrun.novaseq.log
```
- the `/home/proj/stage/bin/git/demultiplexing/scripts/novaseq/checkfornewrun.bash` needs to submit the novaseq demux as an sbatch script:
  - convert the `/home/proj/stage/bin/git/demultiplexing/scripts/novaseq/demux-novaseq.sh` script to an sbatch by adding following headers just after the shebang:

  ```
  #SBATCH --account=development # change to production for the production script
  #SBATCH --ntasks=36
  #SBATCH --time=12:00:00
  #SBATCH --qos=high
  #SBATCH --job-name=demux-novaseq
  #SBATCH --error=/home/proj/stage/logs/demux-novaseq-%j.txt
  #SBATCH --output=/home/proj/stage/logs/demux-novaseq-%j.txt
  ```

  - change the `--loading-threads 3 --processing-threads 12 --writing-threads 3 ` to `--loading-threads 6 --processing-threads 28 --writing-threads 6`
  - change the call `bash ${SCRIPT_DIR}/demux-novaseq.sh ...` to `sbatch ${SCRIPT_DIR/demux-novaseq.sh ...`
- Let the seq-nas-1, nas-6, clinical-nas-2 sync to `hasta:/home/proj/production/runs/novaseq/` (directory can be discussed) (see doc Raw Data Acquisition)

- make test case in the server repo on github (tag: hasta verification)
- run test case
- make implementation plan
- disable demux on thalamus

DoD:
- when demultiplexing happens on hasta
- implementation plan is sent for approval

How to demo:
inform how much faster this is ```scontrol show job <jobID>``` (find <jobID> by looking in /home/proj/stage/logs/checkfornewrun.novaseq.log) (show time by displaying the project log, in the DEMUX run directory)

**Comment by ingkebil** [comment]
Following crontabs need to be moved from rasta to hasta:

# start analyses for families that are ready [every 4th hour]                                                                                                                                  
15 */4 * * * $CRONIC ${HOME}/servers/crontab/analysis-auto.sh >> ${LOG_BASE}/cg.analysis.log 2> >(tee -a ${LOG_BASE}/cg.analysis.log >&2)                                                      
                                                                                                                                                                                               # scan for analyses [every hour]                                                                                                                                                               
54 * * * * $CRONIC ${HOME}/servers/resources/rastapopoulos.scilifelab.se/crontabs/trailblazer-scan.sh >> ${LOG_BASE}/trailblazer.scan.log 2> >(tee -a ${LOG_BASE}/trailblazer.scan.log >&2)    
                                                                                                                                                                                               
# store completed analyses in Housekeeper [every 2nd hour]                                                                                                                                     30 */2 * * * $CRONIC ${HOME}/servers/crontab/store-completed.sh >> ${LOG_BASE}/cg.store.log 2> >(tee -a ${LOG_BASE}/cg.store.log >&2)                                                          
                                                                                                                                                                                               
# upload results for families that are analyzed [every 3rd hour]                                                                                                                               
55 */3 * * * $CRONIC ${HOME}/servers/crontab/upload-auto.sh >> ${LOG_BASE}/cg.upload.log 2> >(tee -a ${LOG_BASE}/cg.upload.log >&2)

**Comment by b4ckm4n** [comment]
- IT has been asked to install bcl2fastq, request is queued.
- got one novaseq run from clinical-nas-2 to hasta: /home/proj/stage/runs/novaseq/181109_A00187_0087_BHFYHFDMXX

**Comment by ingkebil** [comment]
We can change the amount of threads to this:
`--loading-threads 6 --processing-threads 36 --writing-threads 6`

See page 4 of https://docs.google.com/document/d/1WCkoD7OOXj7lJ9-1gtne0N9g7Wpcyiw6O2M1s0-4y3o/edit#heading=h.hzb1idv8aswr

**Comment by henrikstranneheim** [comment]
Stale and solved elsewhere
