### ISSUE TITLE
HiSeqX is demultiplexing on Hasta

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#77]
As a member of TEAPOT, I want to be able to use fastq files from HiSeq X flowcells on Hasta, so I can analyze or reanalyze a case.

Problem: HiSeqX demultiplexing is now running on Rasta.

Suggested solution:

Partly solved here: https://github.com/Clinical-Genomics/demultiplexing/pull/74

Changes need to be made to demultiplexing `scripts/hiseqx/xcheckfornewrun.bash`, `scripts/hiseqx/xdemuxtiles.bash`, `scripts/hiseqx/xdemuxtiles.batch`

- [x] Have IT install same version of bcl2fastq that is installed on Rasta on Hasta

- [x] `scripts/hiseqx/xcheckfornewrun.bash`
  - Don't source bashrc, instead activate correct env (stage or prod)
  - Change params to point to correct directories

- [x] `scripts/hiseqx/xdemuxtiles.bash`
  - Don't source bashrc, instead activate correct env (stage or prod)
  - Change params to point to correct directories
  - Remove copycomplete logic that waits for jobs to be copied to a node

- [x] `scripts/hiseqx/xdemuxtiles.batch`
  - Don't source bashrc, instead activate correct env (stage or prod)
  - Change params to point to correct directories
  - No more copying from input
  - ~~Change params of bcl2fastq to match the ones suggested for NovaSeq (see Novaseq US)~~
  - Refactor copy of output to rename of output

- [ ] remove the copycomplete.txt trigger from deliver and possibly add another trigger?
- [ ] activate the prod env in `checkfornewdemuxonhasta.sh`

- [ ] Create test specification
- [ ] Validate

- [ ] Add crontab entry:
  `... copy crontab entry with xcheckfornewrun.bash from rasta ...`

**Comment by emiliaol** [comment]
@ingkebil Is this still happening in the background for non-complicated FCs? Or is the NAS access denied problem going to interfere with this?

**Comment by ingkebil** [comment]
This is not happening anymore.
