### ISSUE TITLE
x10: detect index for right lane based on lane instead of linenr in samplesheet 

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/demultiplexing#8]
Now, we assume the lane of a sample will on line $lanenr + 2 (2 headers) instead of checking the lane column of the sample sheet. We should get the sample info based on the latter.

**Comment by ingkebil** [comment]
This is in script `xdemuxtiles.batch`

**Comment by henrikstranneheim** [comment]
Stale
