### ISSUE TITLE
Parse NIPT basemask from RunInfo.xml

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/demultiplexing#96]
**When** demultiplexing NIPT runs form the NovaSeq
**I want** the basemask to be derived from RunInfo.xml
**so that** the demultiplexing automation can pick up both regular and NIPT runs[.](https://www.mountaingoatsoftware.com/blog/job-stories-offer-a-viable-alternative-to-user-stories)

#### Problem description:

Currently, when the automation picks up a run ready to be demultiplexed on thalamus, the script `demux-novaseq.bash` uses a hardcoded basemask `Y151I10I10Y151`. NIPT runs however use a basemask of `Y51I8I8Y51`. The basemask information for a NIPT run is stored in the RunInfo.xml and can be parsed form there.

See `/home/hiseq.clinical/STAGE/novaseq/runs/200326_A00689_0120_AHHV7KDRXX` on `thalamus` for examples.

#### Suggested solution:

Parse the basemask from RunInfo.xml. Demultiplexing on hasta uses the function `get_basemask()` in  `/home/proj/production/bin/git/demultiplexing/scripts/demux.functions`, perhaps this can be used as an example.

#### Requirements:

1) Automation can start demultiplexing of NIPT runs automatically with the correct basemask.

**Comment by barrystokman** [comment]
PR: https://github.com/Clinical-Genomics/demultiplexing/pull/106

**Comment by henrikstranneheim** [comment]
Seems done - closing. Reopen if you disagree
